import React from "react";
import { NavLink } from "react-router-dom";

const TextModule = () => {
  const sections = [
    {
      id: 1,
      title: "The Need to Invest",
      content:
        "Learn about the importance of savings. Identify avenues to invest the savings in suitable investment vehicles. Compare historical returns generated by different assets, and know what to expect from your investments...",
    },
    {
      id: 2,
      title: "Regulators, the guardians of capital markets",
      content:
        "Find out who and how the regulators govern the financial markets and also understand different types of financial market participants. Understand the need to regulate the markets...",
    },
  ];

  return (
    <div className="max-w-screen-lg mx-auto p-6 bg-gradient-to-br from-blue-50 to-white dark:from-zinc-900 dark:to-zinc-800 rounded-xl shadow-2xl dark:text-white">
      <header className="text-center mb-12">
        <h1 className="text-7xl font-extrabold text-blue-600 dark:text-blue-400 animate-bounce">
          1
        </h1>
        <h2 className="text-4xl font-bold mt-4 dark:text-white">
          Introduction to Stock Markets
        </h2>
        <div className="flex justify-center gap-6 mt-8">
          <NavLink
            to="/Video-module"
            className="px-6 py-3 bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-lg hover:scale-105 transform transition-all duration-300 dark:bg-blue-700 dark:hover:bg-blue-600"
          >
            🎥 Watch Videos
          </NavLink>
          <a
            href="#"
            className="px-6 py-3 border border-blue-600 text-blue-600 rounded-lg hover:bg-blue-100 hover:scale-105 transform transition-all duration-300 dark:text-blue-300 dark:border-blue-400 dark:hover:bg-blue-600 dark:hover:text-white"
          >
            🇮🇳 हिंदी
          </a>
          <a
            href="#"
            className="px-6 py-3 border border-gray-400 text-gray-600 rounded-lg hover:bg-gray-100 hover:scale-105 transform transition-all duration-300 dark:text-gray-300 dark:border-gray-500 dark:hover:bg-gray-600 dark:hover:text-white"
          >
            📥 Download PDF
          </a>
        </div>
      </header>
      <main className="space-y-8">
        {sections.map((section) => (
          <section
            key={section.id}
            className="p-6 bg-white dark:bg-zinc-700 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300 dark:text-white"
          >
            <h3 className="text-2xl font-semibold mb-3 text-blue-600 dark:text-blue-300">
              {section.title}
            </h3>
            <p className="text-gray-700 dark:text-gray-300">
              {section.content}
            </p>
          </section>
        ))}
      </main>
    </div>
  );
};

export default TextModule;
