import React from "react";
import { NavLink } from "react-router";

const TextModule = () => {
  return (
    <div className="max-w-screen-md mx-auto p-4 mt-10">
      <header className=" mb-8">
        <h1 className="text-7xl font-bold">1</h1>
        <h2 className="text-4xl font-semibold mt-2">
          Introduction to Stock Markets
        </h2>
        <div className="flex justify-center m-8">
          <NavLink
            to={"/Video-module"}
            className="text-blue-500 underline mx-2"
          >
            Watch videos
          </NavLink>
          <a href="#" className="text-blue-500 underline mx-2">
            हिंदी
          </a>
          <a href="#" className="text-blue-500 underline mx-2">
            Download PDF
          </a>
        </div>
      </header>
      <main>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">1. The Need to Invest</h3>
          <p className="text-gray-600 mt-3">
            Learn about the importance of savings. Identify avenues to invest
            the savings in suitable investment vehicles. Compare historical
            returns generated by different assets, and know what to expect from
            you...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">
            2. Regulators, the guardians of capital markets
          </h3>
          <p className="text-gray-600 mt-3">
            Find out who and how the regulators govern the financial markets and
            also understand different types of financial market participants.
            Understand the need to regulate the markets...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">3. Market Intermediaries</h3>
          <p className="text-gray-600 mt-3">
            An overview of the financial intermediaries in the Indian stock
            market and the services they offer...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">4. The IPO Markets (Part 1)</h3>
          <p className="text-gray-600 mt-3">
            Understand the origins of business and the funding environment of
            business. Learn about the different funding stages and...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">5. The IPO Markets (Part 2)</h3>
          <p className="text-gray-600 mt-3">
            Understand the origins of business and the funding environment of
            business. Learn about the different funding stages and...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">6. The Stock Market</h3>
          <p className="text-gray-600 mt-3">
            Understand the origins of business and the funding environment of
            business. Learn about the different funding stages and...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">7. The Stock Market Index</h3>
          <p className="text-gray-600 mt-3">
            Understand the origins of business and the funding environment of
            business. Learn about the different funding stages and...
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-2xl font-medium">8. Commonly Used Jargons</h3>
          <p className="text-gray-600 mt-3">
            Understand the origins of business and the funding environment of
            business. Learn about the different funding stages and...
          </p>
        </section>
      </main>
    </div>
  );
};

export default TextModule;
